const words = [
    { english: "a, an", turkish: "bir (belgisiz artikel)" },
    { english: "about", turkish: "hakkında, yaklaşık", type: "prep., adv." },
    { english: "above", turkish: "üstünde, yukarıda", type: "prep., adv." },
    { english: "across", turkish: "karşısında, boyunca", type: "prep., adv." },
    { english: "action", turkish: "eylem, hareket", type: "n." },
    { english: "activity", turkish: "aktivite, faaliyet", type: "n." },
    { english: "actor", turkish: "aktör", type: "n." },
    { english: "actress", turkish: "aktris", type: "n." },
    { english: "add", turkish: "eklemek", type: "v." },
    { english: "address", turkish: "adres", type: "n." },
    { english: "adult", turkish: "yetişkin", type: "n." },
    { english: "advice", turkish: "tavsiye", type: "n." },
    { english: "afraid", turkish: "korkmuş", type: "adj." },
    { english: "after", turkish: "sonra", type: "prep." },
    { english: "afternoon", turkish: "öğleden sonra", type: "n." },
    { english: "again", turkish: "tekrar", type: "adv." },
    { english: "age", turkish: "yaş", type: "n." },
    { english: "ago", turkish: "önce", type: "adv." },
    { english: "agree", turkish: "kabul etmek, aynı fikirde olmak", type: "v." },
    { english: "air", turkish: "hava", type: "n." },
    { english: "airport", turkish: "havalimanı", type: "n." },
    { english: "all", turkish: "hepsi, tüm", type: "det., pron." },
    { english: "also", turkish: "ayrıca, da/de", type: "adv." },
    { english: "always", turkish: "her zaman", type: "adv." },
    { english: "amazing", turkish: "harika, şaşırtıcı", type: "adj." },
    { english: "and", turkish: "ve", type: "conj." },
    { english: "angry", turkish: "kızgın", type: "adj." },
    { english: "animal", turkish: "hayvan", type: "n." },
    { english: "another", turkish: "başka, diğer", type: "det./pron." },
    { english: "answer", turkish: "cevap, cevaplamak", type: "n., v." },
    { english: "any", turkish: "herhangi bir", type: "det., pron." },
    { english: "anyone", turkish: "herhangi biri", type: "pron." },
    { english: "anything", turkish: "herhangi bir şey", type: "pron." },
    { english: "apartment", turkish: "daire", type: "n." },
    { english: "apple", turkish: "elma", type: "n." },
    { english: "April", turkish: "Nisan", type: "n." },
    { english: "area", turkish: "alan, bölge", type: "n." },
    { english: "arm", turkish: "kol", type: "n." },
    { english: "around", turkish: "etrafında, civarında", type: "prep., adv." },
    { english: "arrive", turkish: "varmak, ulaşmak", type: "v." },
    { english: "art", turkish: "sanat", type: "n." },
    { english: "article", turkish: "makale", type: "n." },
    { english: "artist", turkish: "sanatçı", type: "n." },
    { english: "as", turkish: "olarak, gibi", type: "prep." },
    { english: "ask", turkish: "sormak", type: "v." },
    { english: "at", turkish: "-de/-da, -te/-ta", type: "prep." },
    { english: "August", turkish: "Ağustos", type: "n." },
    { english: "aunt", turkish: "teyze, hala", type: "n." },
    { english: "autumn", turkish: "sonbahar", type: "n." },
    { english: "away", turkish: "uzakta", type: "adv." },
    { english: "baby", turkish: "bebek", type: "n." },
    { english: "back", turkish: "geri, sırt", type: "n., adv." },
    { english: "bad", turkish: "kötü", type: "adj." },
    { english: "bag", turkish: "çanta", type: "n." },
    { english: "ball", turkish: "top", type: "n." },
    { english: "banana", turkish: "muz", type: "n." },
    { english: "band", turkish: "grup, bant", type: "n." },
    { english: "bank", turkish: "banka", type: "n." },
    { english: "bath", turkish: "banyo", type: "n." },
    { english: "bathroom", turkish: "banyo", type: "n." },
    { english: "be", turkish: "olmak", type: "v." },
    { english: "beach", turkish: "plaj", type: "n." },
    { english: "beautiful", turkish: "güzel", type: "adj." },
    { english: "because", turkish: "çünkü", type: "conj." },
    { english: "become", turkish: "olmak, haline gelmek", type: "v." },
    { english: "bed", turkish: "yatak", type: "n." },
    { english: "bedroom", turkish: "yatak odası", type: "n." },
    { english: "beer", turkish: "bira", type: "n." },
    { english: "before", turkish: "önce", type: "prep." },
    { english: "begin", turkish: "başlamak", type: "v." },
    { english: "beginning", turkish: "başlangıç", type: "n." },
    { english: "behind", turkish: "arkasında", type: "prep., adv." },
    { english: "believe", turkish: "inanmak", type: "v." },
    { english: "below", turkish: "aşağıda, altında", type: "adv., prep." },
    { english: "best", turkish: "en iyi", type: "adj." },
    { english: "better", turkish: "daha iyi", type: "adj." },
    { english: "between", turkish: "arasında", type: "prep." },
    { english: "bicycle", turkish: "bisiklet", type: "n." },
    { english: "big", turkish: "büyük", type: "adj." },
    { english: "bike", turkish: "bisiklet", type: "n." },
    { english: "bill", turkish: "fatura", type: "n." },
    { english: "bird", turkish: "kuş", type: "n." },
    { english: "birthday", turkish: "doğum günü", type: "n." },
    { english: "black", turkish: "siyah", type: "adj., n." },
    { english: "blog", turkish: "blog", type: "n." },
    { english: "blonde", turkish: "sarışın", type: "adj." },
    { english: "blue", turkish: "mavi", type: "adj., n." },
    { english: "boat", turkish: "tekne", type: "n." },
    { english: "body", turkish: "vücut", type: "n." },
    { english: "book", turkish: "kitap", type: "n." },
    { english: "boot", turkish: "bot", type: "n." },
    { english: "bored", turkish: "sıkılmış", type: "adj." },
    { english: "boring", turkish: "sıkıcı", type: "adj." },
    { english: "born", turkish: "doğmak", type: "v." },
    { english: "both", turkish: "her ikisi", type: "det./pron." },
    { english: "bottle", turkish: "şişe", type: "n." },
    { english: "box", turkish: "kutu", type: "n." },
    { english: "boy", turkish: "erkek çocuk", type: "n." },
    { english: "boyfriend", turkish: "erkek arkadaş", type: "n." },
    { english: "bread", turkish: "ekmek", type: "n." },
    { english: "break", turkish: "kırmak, mola", type: "v., n." },
    { english: "breakfast", turkish: "kahvaltı", type: "n." },
    { english: "bring", turkish: "getirmek", type: "v." },
    { english: "brother", turkish: "erkek kardeş", type: "n." },
    { english: "brown", turkish: "kahverengi", type: "adj., n." },
    { english: "build", turkish: "inşa etmek", type: "v." },
    { english: "building", turkish: "bina", type: "n." },
    { english: "bus", turkish: "otobüs", type: "n." },
    { english: "business", turkish: "iş", type: "n." },
    { english: "busy", turkish: "meşgul", type: "adj." },
    { english: "but", turkish: "ama, fakat", type: "conj." },
    { english: "butter", turkish: "tereyağı", type: "n." },
    { english: "buy", turkish: "satın almak", type: "v." },
    { english: "by", turkish: "tarafından, yanında", type: "prep." },
    { english: "bye", turkish: "hoşça kal", type: "exclam." },
    { english: "cafe", turkish: "kafe", type: "n." },
    { english: "cake", turkish: "pasta", type: "n." },
    { english: "call", turkish: "aramak, çağırmak", type: "v., n." },
    { english: "camera", turkish: "kamera", type: "n." },
    { english: "can", turkish: "-ebilmek", type: "modal v." },
    { english: "cannot", turkish: "-ememek", type: "modal v." },
    { english: "capital", turkish: "başkent, büyük harf", type: "n., adj." },
    { english: "car", turkish: "araba", type: "n." },
    { english: "card", turkish: "kart", type: "n." },
    { english: "career", turkish: "kariyer", type: "n." },
    { english: "carrot", turkish: "havuç", type: "n." },
    { english: "carry", turkish: "taşımak", type: "v." },
    { english: "cat", turkish: "kedi", type: "n." },
    { english: "CD", turkish: "CD", type: "n." },
    { english: "cent", turkish: "sent", type: "n." },
    { english: "centre", turkish: "merkez", type: "n." },
    { english: "century", turkish: "yüzyıl", type: "n." },
    { english: "chair", turkish: "sandalye", type: "n." },
    { english: "change", turkish: "değişmek, değişiklik", type: "v., n." },
    { english: "chart", turkish: "grafik, tablo", type: "n." },
    { english: "cheap", turkish: "ucuz", type: "adj." },
    { english: "check", turkish: "kontrol etmek", type: "v." },
    { english: "cheese", turkish: "peynir", type: "n." },
    { english: "chicken", turkish: "tavuk", type: "n." },
    { english: "child", turkish: "çocuk", type: "n." },
    { english: "chocolate", turkish: "çikolata", type: "n." },
    { english: "choose", turkish: "seçmek", type: "v." },
    { english: "cinema", turkish: "sinema", type: "n." },
    { english: "city", turkish: "şehir", type: "n." },
    { english: "class", turkish: "sınıf", type: "n." },
    { english: "classroom", turkish: "sınıf (oda)", type: "n." },
    { english: "clean", turkish: "temiz, temizlemek", type: "adj., v." },
    { english: "climb", turkish: "tırmanmak", type: "v." },
    { english: "clock", turkish: "saat", type: "n." },
    { english: "close", turkish: "kapatmak", type: "v." },
    { english: "clothes", turkish: "kıyafetler", type: "n." },
    { english: "club", turkish: "kulüp", type: "n." },
    { english: "coat", turkish: "palto, ceket", type: "n." },
    { english: "coffee", turkish: "kahve", type: "n." },
    { english: "cold", turkish: "soğuk", type: "adj., n." },
    { english: "college", turkish: "kolej, yüksekokul", type: "n." },
    { english: "colour", turkish: "renk", type: "n." },
    { english: "come", turkish: "gelmek", type: "v." },
    { english: "common", turkish: "yaygın, ortak", type: "adj." },
    { english: "company", turkish: "şirket", type: "n." },
    { english: "compare", turkish: "karşılaştırmak", type: "v." },
    { english: "complete", turkish: "tamamlamak, tam", type: "adj., v." },
    { english: "computer", turkish: "bilgisayar", type: "n." },
    { english: "concert", turkish: "konser", type: "n." },
    { english: "conversation", turkish: "konuşma, sohbet", type: "n." },
    { english: "cook", turkish: "pişirmek", type: "v." },
    { english: "cooking", turkish: "yemek pişirme", type: "n." },
    { english: "cool", turkish: "havalı, serin", type: "adj." },
    { english: "correct", turkish: "doğru, düzeltmek", type: "adj., v." },
    { english: "cost", turkish: "maliyet, mal olmak", type: "n., v." },
    { english: "could", turkish: "-ebilirdi", type: "modal v." },
    { english: "country", turkish: "ülke", type: "n." },
    { english: "course", turkish: "kurs, ders", type: "n." },
    { english: "cousin", turkish: "kuzen", type: "n." },
    { english: "cow", turkish: "inek", type: "n." },
    { english: "cream", turkish: "krema", type: "n." },
    { english: "create", turkish: "oluşturmak", type: "v." },
    { english: "culture", turkish: "kültür", type: "n." },
    { english: "cup", turkish: "fincan, kupa", type: "n." },
    { english: "customer", turkish: "müşteri", type: "n." },
    { english: "cut", turkish: "kesmek", type: "v." },
    { english: "dad", turkish: "baba", type: "n." },
    { english: "dance", turkish: "dans, dans etmek", type: "n., v." },
    { english: "dancer", turkish: "dansçı", type: "n." },
    { english: "dancing", turkish: "dans etme", type: "n." },
    { english: "dangerous", turkish: "tehlikeli", type: "adj." },
    { english: "dark", turkish: "karanlık", type: "adj." },
    { english: "date", turkish: "tarih, randevu", type: "n." },
    { english: "daughter", turkish: "kız evlat", type: "n." },
    { english: "day", turkish: "gün", type: "n." },
    { english: "dear", turkish: "sevgili", type: "adj." },
    { english: "December", turkish: "Aralık", type: "n." },
    { english: "decide", turkish: "karar vermek", type: "v." },
    { english: "delicious", turkish: "lezzetli", type: "adj." },
    { english: "describe", turkish: "tanımlamak", type: "v." },
    { english: "description", turkish: "tanım", type: "n." },
    { english: "design", turkish: "tasarım, tasarlamak", type: "n., v." },
    { english: "desk", turkish: "çalışma masası", type: "n." },
    { english: "detail", turkish: "detay", type: "n." },
    { english: "dialogue", turkish: "diyalog", type: "n." },
    { english: "dictionary", turkish: "sözlük", type: "n." },
    { english: "die", turkish: "ölmek", type: "v." },
    { english: "diet", turkish: "diyet", type: "n." },
    { english: "difference", turkish: "fark", type: "n." },
    { english: "different", turkish: "farklı", type: "adj." },
    { english: "difficult", turkish: "zor", type: "adj." },
    { english: "dinner", turkish: "akşam yemeği", type: "n." },
    { english: "dirty", turkish: "kirli", type: "adj." },
    { english: "discuss", turkish: "tartışmak", type: "v." },
    { english: "dish", turkish: "tabak, yemek", type: "n." },
    { english: "do", turkish: "yapmak", type: "v." },
    { english: "doctor", turkish: "doktor", type: "n." },
    { english: "dog", turkish: "köpek", type: "n." },
    { english: "dollar", turkish: "dolar", type: "n." },
    { english: "door", turkish: "kapı", type: "n." },
    { english: "down", turkish: "aşağı", type: "adv., prep." },
    { english: "downstairs", turkish: "alt kat", type: "adv." },
    { english: "draw", turkish: "çizmek", type: "v." },
    { english: "dress", turkish: "elbise, giyinmek", type: "n., v." },
    { english: "drink", turkish: "içmek, içecek", type: "n., v." },
    { english: "drive", turkish: "sürmek", type: "v." },
    { english: "driver", turkish: "sürücü", type: "n." },
    { english: "during", turkish: "süresince", type: "prep." },
    { english: "DVD", turkish: "DVD", type: "n." },
    { english: "each", turkish: "her biri", type: "det./pron./adv." },
    { english: "ear", turkish: "kulak", type: "n." },
    { english: "early", turkish: "erken", type: "adj., adv." },
    { english: "east", turkish: "doğu", type: "n., adj., adv." },
    { english: "easy", turkish: "kolay", type: "adj." },
    { english: "eat", turkish: "yemek yemek", type: "v." },
    { english: "egg", turkish: "yumurta", type: "n." },
    { english: "eight", turkish: "sekiz", type: "number" },
    { english: "eighteen", turkish: "on sekiz", type: "number" },
    { english: "eighty", turkish: "seksen", type: "number" },
    { english: "elephant", turkish: "fil", type: "n." },
    { english: "eleven", turkish: "on bir", type: "number" },
    { english: "else", turkish: "başka", type: "adv." },
    { english: "email", turkish: "e-posta", type: "n., v." },
    { english: "end", turkish: "son, bitirmek", type: "n., v." },
    { english: "enjoy", turkish: "hoşlanmak, keyif almak", type: "v." },
    { english: "enough", turkish: "yeterli", type: "det., pron., adv." },
    { english: "euro", turkish: "euro", type: "n." },
    { english: "even", turkish: "bile, hatta", type: "adv." },
    { english: "evening", turkish: "akşam", type: "n." },
    { english: "event", turkish: "olay, etkinlik", type: "n." },
    { english: "ever", turkish: "hiç, herhangi bir zaman", type: "adv." },
    { english: "every", turkish: "her", type: "det." },
    { english: "everybody", turkish: "herkes", type: "pron." },
    { english: "everyone", turkish: "herkes", type: "pron." },
    { english: "everything", turkish: "her şey", type: "pron." },
    { english: "exam", turkish: "sınav", type: "n." },
    { english: "example", turkish: "örnek", type: "n." },
    { english: "excited", turkish: "heyecanlı", type: "adj." },
    { english: "exciting", turkish: "heyecan verici", type: "adj." },
    { english: "exercise", turkish: "egzersiz, alıştırma", type: "n., v." },
    { english: "expensive", turkish: "pahalı", type: "adj." },
    { english: "explain", turkish: "açıklamak", type: "v." },
    { english: "extra", turkish: "ekstra", type: "adj." },
    { english: "eye", turkish: "göz", type: "n." },
    { english: "face", turkish: "yüz", type: "n." },
    { english: "fact", turkish: "gerçek", type: "n." },
    { english: "fall", turkish: "düşmek", type: "v." },
    { english: "false", turkish: "yanlış", type: "adj." },
    { english: "family", turkish: "aile", type: "n., adj." },
    { english: "famous", turkish: "ünlü", type: "adj." },
    { english: "fantastic", turkish: "harika", type: "adj." },
    { english: "far", turkish: "uzak", type: "adv." },
    { english: "farm", turkish: "çiftlik", type: "n." },
    { english: "farmer", turkish: "çiftçi", type: "n." },
    { english: "fast", turkish: "hızlı", type: "adj., adv." },
    { english: "fat", turkish: "şişman", type: "adj." },
    { english: "father", turkish: "baba", type: "n." },
    { english: "favourite", turkish: "favori", type: "adj., n." },
    { english: "February", turkish: "Şubat", type: "n." },
    { english: "feel", turkish: "hissetmek", type: "v." },
    { english: "feeling", turkish: "his, duygu", type: "n." },
    { english: "festival", turkish: "festival", type: "n." },
    { english: "few", turkish: "az", type: "det./adj., pron." },
    { english: "fifteen", turkish: "on beş", type: "number" },
    { english: "fifth", turkish: "beşinci", type: "number" },
    { english: "fifty", turkish: "elli", type: "number" },
    { english: "fill", turkish: "doldurmak", type: "v." },
    { english: "film", turkish: "film", type: "n." },
    { english: "final", turkish: "son, final", type: "adj." },
    { english: "find", turkish: "bulmak", type: "v." },
    { english: "fine", turkish: "iyi, güzel", type: "adj." },
    { english: "finish", turkish: "bitirmek", type: "v." },
    { english: "fire", turkish: "ateş", type: "n." },
    { english: "first", turkish: "birinci, ilk", type: "det./number, adv." },
    { english: "fish", turkish: "balık", type: "n." },
    { english: "five", turkish: "beş", type: "number" },
    { english: "flat", turkish: "daire", type: "n." },
    { english: "flight", turkish: "uçuş", type: "n." },
    { english: "floor", turkish: "kat, zemin", type: "n." },
    { english: "flower", turkish: "çiçek", type: "n." },
    { english: "fly", turkish: "uçmak", type: "v." },
    { english: "follow", turkish: "takip etmek", type: "v." },
    { english: "food", turkish: "yiyecek", type: "n." },
    { english: "foot", turkish: "ayak", type: "n." },
    { english: "football", turkish: "futbol", type: "n." },
    { english: "for", turkish: "için", type: "prep." },
    { english: "forget", turkish: "unutmak", type: "v." },
    { english: "form", turkish: "form, biçim", type: "n., v." },
    { english: "forty", turkish: "kırk", type: "number" },
    { english: "four", turkish: "dört", type: "number" },
    { english: "fourteen", turkish: "on dört", type: "number" },
    { english: "fourth", turkish: "dördüncü", type: "number" },
    { english: "free", turkish: "ücretsiz, serbest", type: "adj." },
    { english: "Friday", turkish: "Cuma", type: "n." },
    { english: "friend", turkish: "arkadaş", type: "n." },
    { english: "friendly", turkish: "arkadaş canlısı", type: "adj." },
    { english: "from", turkish: "-den/-dan", type: "prep." },
    { english: "front", turkish: "ön", type: "n., adj." },
    { english: "fruit", turkish: "meyve", type: "n." },
    { english: "full", turkish: "dolu", type: "adj." },
    { english: "fun", turkish: "eğlence", type: "n." },
    { english: "funny", turkish: "komik", type: "adj." },
    { english: "future", turkish: "gelecek", type: "n." },
    { english: "game", turkish: "oyun", type: "n." },
    { english: "garden", turkish: "bahçe", type: "n." },
    { english: "geography", turkish: "coğrafya", type: "n." },
    { english: "get", turkish: "almak, elde etmek", type: "v." },
    { english: "girl", turkish: "kız", type: "n." },
    { english: "girlfriend", turkish: "kız arkadaş", type: "n." },
    { english: "give", turkish: "vermek", type: "v." },
    { english: "glass", turkish: "cam, bardak", type: "n." },
    { english: "go", turkish: "gitmek", type: "v." },
    { english: "good", turkish: "iyi", type: "adj." },
    { english: "goodbye", turkish: "hoşça kal", type: "exclam./n." },
    { english: "grandfather", turkish: "büyükbaba", type: "n." },
    { english: "grandmother", turkish: "büyükanne", type: "n." },
    { english: "grandparent", turkish: "büyükanne/büyükbaba", type: "n." },
    { english: "great", turkish: "harika, büyük", type: "adj." },
    { english: "green", turkish: "yeşil", type: "adj., n." },
    { english: "grey", turkish: "gri", type: "adj., n." },
    { english: "group", turkish: "grup", type: "n." },
    { english: "grow", turkish: "büyümek", type: "v." },
    { english: "guess", turkish: "tahmin, tahmin etmek", type: "v., n." },
    { english: "guitar", turkish: "gitar", type: "n." },
    { english: "gym", turkish: "spor salonu", type: "n." },
    { english: "hair", turkish: "saç", type: "n." },
    { english: "half", turkish: "yarım", type: "n., det./pron." },
    { english: "hand", turkish: "el", type: "n." },
    { english: "happen", turkish: "olmak", type: "v." },
    { english: "happy", turkish: "mutlu", type: "adj." },
    { english: "hard", turkish: "zor, sert", type: "adj., adv." },
    { english: "hat", turkish: "şapka", type: "n." },
    { english: "hate", turkish: "nefret etmek", type: "v." },
    { english: "have", turkish: "sahip olmak", type: "v." },
    { english: "have to", turkish: "zorunda olmak", type: "modal v." },
    { english: "he", turkish: "o (erkek)", type: "pron." },
    { english: "head", turkish: "baş, kafa", type: "n." },
    { english: "health", turkish: "sağlık", type: "n." },
    { english: "healthy", turkish: "sağlıklı", type: "adj." },
    { english: "hear", turkish: "duymak", type: "v." },
    { english: "hello", turkish: "merhaba", type: "exclam./n." },
    { english: "help", turkish: "yardım, yardım etmek", type: "v., n." },
    { english: "her", turkish: "onun (kadın)", type: "pron., det." },
    { english: "here", turkish: "burada", type: "adv." },
    { english: "hey", turkish: "hey", type: "exclam." },
    { english: "hi", turkish: "selam", type: "exclam." },
    { english: "high", turkish: "yüksek", type: "adj." },
    { english: "him", turkish: "ona (erkek)", type: "pron." },
    { english: "his", turkish: "onun (erkek)", type: "det." },
    { english: "history", turkish: "tarih", type: "n." },
    { english: "hobby", turkish: "hobi", type: "n." },
    { english: "holiday", turkish: "tatil", type: "n." },
    { english: "home", turkish: "ev", type: "n., adv." },
    { english: "homework", turkish: "ev ödevi", type: "n." },
    { english: "hope", turkish: "umut etmek", type: "v." },
    { english: "horse", turkish: "at", type: "n." },
    { english: "hospital", turkish: "hastane", type: "n." },
    { english: "hot", turkish: "sıcak", type: "adj." },
    { english: "hotel", turkish: "otel", type: "n." },
    { english: "hour", turkish: "saat", type: "n." },
    { english: "house", turkish: "ev", type: "n." },
    { english: "how", turkish: "nasıl", type: "adv." },
    { english: "however", turkish: "ancak, fakat", type: "adv." },
    { english: "hundred", turkish: "yüz", type: "number" },
    { english: "hungry", turkish: "aç", type: "adj." },
    { english: "husband", turkish: "koca", type: "n." },
    { english: "I", turkish: "ben", type: "pron." },
    { english: "ice", turkish: "buz", type: "n." },
    { english: "ice cream", turkish: "dondurma", type: "n." },
    { english: "idea", turkish: "fikir", type: "n." },
    { english: "if", turkish: "eğer", type: "conj." },
    { english: "imagine", turkish: "hayal etmek", type: "v." },
    { english: "important", turkish: "önemli", type: "adj." },
    { english: "improve", turkish: "geliştirmek", type: "v." },
    { english: "in", turkish: "içinde", type: "prep., adv." },
    { english: "include", turkish: "içermek", type: "v." },
    { english: "information", turkish: "bilgi", type: "n." },
    { english: "interest", turkish: "ilgi, ilgilenmek", type: "n., v." },
    { english: "interested", turkish: "ilgili", type: "adj." },
    { english: "interesting", turkish: "ilginç", type: "adj." },
    { english: "internet", turkish: "internet", type: "n." },
    { english: "interview", turkish: "görüşme, röportaj", type: "n., v." },
    { english: "into", turkish: "içine", type: "prep." },
    { english: "introduce", turkish: "tanıştırmak", type: "v." },
    { english: "island", turkish: "ada", type: "n." },
    { english: "it", turkish: "o (cansız)", type: "pron." },
    { english: "its", turkish: "onun (cansız)", type: "det." },
    { english: "jacket", turkish: "ceket", type: "n." },
    { english: "January", turkish: "Ocak", type: "n." },
    { english: "jeans", turkish: "kot pantolon", type: "n." },
    { english: "job", turkish: "iş", type: "n." },
    { english: "join", turkish: "katılmak", type: "v." },
    { english: "journey", turkish: "yolculuk", type: "n." },
    { english: "juice", turkish: "meyve suyu", type: "n." },
    { english: "July", turkish: "Temmuz", type: "n." },
    { english: "June", turkish: "Haziran", type: "n." },
    { english: "just", turkish: "sadece", type: "adv." },
    { english: "keep", turkish: "tutmak, saklamak", type: "v." },
    { english: "key", turkish: "anahtar", type: "n., adj." },
    { english: "kilometre", turkish: "kilometre", type: "n." },
    { english: "kind", turkish: "tür, çeşit", type: "n." },
    { english: "kitchen", turkish: "mutfak", type: "n." },
    { english: "know", turkish: "bilmek", type: "v." },
    { english: "land", turkish: "kara, toprak", type: "n." },
    { english: "language", turkish: "dil", type: "n." },
    { english: "large", turkish: "büyük", type: "adj." },
    { english: "last", turkish: "son", type: "det." },
    { english: "late", turkish: "geç", type: "adj., adv." },
    { english: "later", turkish: "daha sonra", type: "adv." },
    { english: "laugh", turkish: "gülmek", type: "v., n." },
    { english: "learn", turkish: "öğrenmek", type: "v." },
    { english: "leave", turkish: "ayrılmak", type: "v." },
    { english: "left", turkish: "sol", type: "adj., adv., n." },
    { english: "leg", turkish: "bacak", type: "n." },
    { english: "lesson", turkish: "ders", type: "n." },
    { english: "let", turkish: "izin vermek", type: "v." },
    { english: "letter", turkish: "mektup, harf", type: "n." },
    { english: "library", turkish: "kütüphane", type: "n." },
    { english: "lie", turkish: "yalan söylemek", type: "v." },
    { english: "life", turkish: "hayat", type: "n." },
    { english: "light", turkish: "ışık, hafif", type: "n., adj." },
    { english: "like", turkish: "gibi", type: "prep." },
    { english: "line", turkish: "çizgi", type: "n." },
    { english: "lion", turkish: "aslan", type: "n." },
    { english: "list", turkish: "liste", type: "n., v." },
    { english: "listen", turkish: "dinlemek", type: "v." },
    { english: "little", turkish: "küçük", type: "adj., det./pron." },
    { english: "live", turkish: "yaşamak", type: "v." },
    { english: "local", turkish: "yerel", type: "adj." },
    { english: "long", turkish: "uzun", type: "adj., adv." },
    { english: "look", turkish: "bakmak", type: "v." },
    { english: "lose", turkish: "kaybetmek", type: "v." },
    { english: "lot", turkish: "çok", type: "pron., det., adv." },
    { english: "love", turkish: "aşk, sevmek", type: "n., v." },
    { english: "lunch", turkish: "öğle yemeği", type: "n." },
    { english: "machine", turkish: "makine", type: "n." },
    { english: "magazine", turkish: "dergi", type: "n." },
    { english: "main", turkish: "ana, temel", type: "adj." },
    { english: "make", turkish: "yapmak", type: "v." },
    { english: "man", turkish: "adam", type: "n." },
    { english: "many", turkish: "çok", type: "det./pron." },
    { english: "map", turkish: "harita", type: "n." },
    { english: "March", turkish: "Mart", type: "n." },
    { english: "market", turkish: "pazar, market", type: "n." },
    { english: "married", turkish: "evli", type: "adj." },
    { english: "match", turkish: "maç, eşleşmek", type: "n., v." },
    { english: "May", turkish: "Mayıs", type: "n." },
    { english: "maybe", turkish: "belki", type: "adv." },
    { english: "me", turkish: "beni, bana", type: "pron." },
    { english: "meal", turkish: "öğün", type: "n." },
    { english: "mean", turkish: "anlamına gelmek", type: "v." },
    { english: "meaning", turkish: "anlam", type: "n." },
    { english: "meat", turkish: "et", type: "n." },
    { english: "meet", turkish: "buluşmak, tanışmak", type: "v." },
    { english: "meeting", turkish: "toplantı", type: "n." },
    { english: "member", turkish: "üye", type: "n." },
    { english: "menu", turkish: "menü", type: "n." },
    { english: "message", turkish: "mesaj", type: "n." },
    { english: "metre", turkish: "metre", type: "n." },
    { english: "midnight", turkish: "gece yarısı", type: "n." },
    { english: "mile", turkish: "mil", type: "n." },
    { english: "milk", turkish: "süt", type: "n." },
    { english: "million", turkish: "milyon", type: "number" },
    { english: "minute", turkish: "dakika", type: "n." },
    { english: "miss", turkish: "özlemek, kaçırmak", type: "v." },
    { english: "mistake", turkish: "hata", type: "n." },
    { english: "model", turkish: "model", type: "n." },
    { english: "modern", turkish: "modern", type: "adj." },
    { english: "moment", turkish: "an", type: "n." },
    { english: "Monday", turkish: "Pazartesi", type: "n." },
    { english: "money", turkish: "para", type: "n." },
    { english: "month", turkish: "ay", type: "n." },
    { english: "more", turkish: "daha fazla", type: "det./pron., adv." },
    { english: "morning", turkish: "sabah", type: "n." },
    { english: "most", turkish: "en çok", type: "det./pron., adv." },
    { english: "mother", turkish: "anne", type: "n." },
    { english: "mountain", turkish: "dağ", type: "n." },
    { english: "mouse", turkish: "fare", type: "n." },
    { english: "mouth", turkish: "ağız", type: "n." },
    { english: "move", turkish: "hareket etmek", type: "v." },
    { english: "movie", turkish: "film", type: "n." },
    { english: "much", turkish: "çok", type: "det./pron., adv." },
    { english: "mum", turkish: "anne", type: "n." },
    { english: "museum", turkish: "müze", type: "n." },
    { english: "music", turkish: "müzik", type: "n." },
    { english: "must", turkish: "zorunda olmak", type: "modal v." },
    { english: "my", turkish: "benim", type: "det." },
    { english: "name", turkish: "isim", type: "n., v." },
    { english: "natural", turkish: "doğal", type: "adj." },
    { english: "near", turkish: "yakın", type: "prep., adj., adv." },
    { english: "need", turkish: "ihtiyaç duymak", type: "v." },
    { english: "negative", turkish: "olumsuz", type: "adj." },
    { english: "neighbour", turkish: "komşu", type: "n." },
    { english: "never", turkish: "asla", type: "adv." },
    { english: "new", turkish: "yeni", type: "adj." },
    { english: "news", turkish: "haber", type: "n." },
    { english: "newspaper", turkish: "gazete", type: "n." },
    { english: "next", turkish: "sonraki", type: "adj., adv." },
    { english: "next to", turkish: "yanında", type: "prep." },
    { english: "nice", turkish: "güzel, hoş", type: "adj." },
    { english: "night", turkish: "gece", type: "n." },
    { english: "nine", turkish: "dokuz", type: "number" },
    { english: "nineteen", turkish: "on dokuz", type: "number" },
    { english: "ninety", turkish: "doksan", type: "number" },
    { english: "no", turkish: "hayır", type: "exclam., det." }

];

let currentIndex = 0;

function updateCard() {
    const wordEnglish = document.getElementById("wordEnglish");
    const wordTurkish = document.getElementById("wordTurkish");

    wordEnglish.textContent = words[currentIndex].english;
    wordTurkish.textContent = words[currentIndex].turkish;
}

function nextWord() {
    const card = document.querySelector(".card");
    card.classList.add("flip-animation-right");
    setTimeout(() => {
        currentIndex = (currentIndex + 1) % words.length;
        updateCard();
        card.classList.remove("flip-animation-right");
    }, 600); 
}

function prevWord() {
    const card = document.querySelector(".card");
    card.classList.add("flip-animation-left");
    setTimeout(() => {
        currentIndex = (currentIndex - 1 + words.length) % words.length;
        updateCard();
        card.classList.remove("flip-animation-left");
    }, 600); 
}

function playSound() {
    const wordEnglish = document.getElementById("wordEnglish").textContent;

    const utterance = new SpeechSynthesisUtterance(wordEnglish);
    utterance.lang = "en-US"; 
    speechSynthesis.speak(utterance);
}

document.addEventListener("DOMContentLoaded", updateCard);

